---
- name:  Gather some variables
  include_vars: "var.yaml"

- name: Creates directory DOC_ROOT
  file:
    path: /var/www/{{ item }}/DOC_ROOT
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0754
    recurse: yes
  with_items: "{{ domains }}"

- name: Creates directory tmp
  file:
    path: /var/www/{{ item }}/tmp
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0777
    recurse: yes
  with_items: "{{ domains }}"

- name: Creates directory sessions
  file:
    path: /var/www/{{ item }}/sessions
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0777
    recurse: yes
  with_items: "{{ domains }}"

- name: Creates directory logs
  file:
    path: /var/www/{{ item }}/logs
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0777
    recurse: yes
  with_items: "{{ domains }}"


- name: Add simple index.html
  template:
    src: "templates/index.html.j2"
    dest: "/var/www/{{ item }}/DOC_ROOT/index.html"
    owner: root
    group: root
    mode: 0644
  vars:
    t_domain: "{{ item }}"
  with_items: "{{ domains }}"
  notify: restart apache


