---
- name: "Include variables"
  include_vars: "debian.yaml"

- name: "Ensure required PHP packages are present"
  apt:
    name: "{{ php_packages }}"
    state: present

- name: "create check PHP install file"
  template: 
    src: check.php 
    dest: /var/www/site.ru/DOC_ROOT/check.php
    owner: site.ru
    group: site.ru

